### ISSUE TITLE
摄像头配网不成功

### ISSUE THREAD

**Issue by liuxin2533** [TuyaInc/tuyasmart_camera_android_sdk#10]
使用本SKD里的demo进行摄像头wifi配网，摄像头是蓝灯闪烁，根据说明书来看，摄像头是配网成功的。但是demo提示设备连接异常，在设备列表里也找不到设备，请问这个是什么情况呢？

摄像头：萤石TYQ2C
手机型号：荣耀magic2
安卓版本：9.0.0.188
wifi：2.4GHz ，WAP2 PSK

![image](https://user-images.githubusercontent.com/47419242/56952615-484b1c00-6b6d-11e9-87b2-b32beff377d0.png)

**Comment by Tuya-DJ** [comment]
请查看一下你的Wi-Fi密码是否正确，ipc的配网流程和其他设备是一样的

**Comment by liuxin2533** [comment]
> 请查看一下你的Wi-Fi密码是否正确，ipc的配网流程和其他设备是一样的

wifi密码是正确的，摄像头已经提示配网成功了。demo提示设备连接异常

**Comment by liuxin2533** [comment]
> 请查看一下你的Wi-Fi密码是否正确，ipc的配网流程和其他设备是一样的

重试了很多次都是这样。

**Comment by Tuya-DJ** [comment]
如果摄像头已经配网成功的话，设备列表那边就会有该摄像头项

**Comment by liuxin2533** [comment]
> 如果摄像头已经配网成功的话，设备列表那边就会有该摄像头项

问题就是没有该摄像头，想请教是什么原因呢？

**Comment by Tuya-DJ** [comment]
可以参考公版的配网:https://tuyainc.github.io/tuyasmart_home_android_sdk_doc/zh-hans/resource/Activator_wifi.html

**Comment by liuxin2533** [comment]
> 如果摄像头已经配网成功的话，设备列表那边就会有该摄像头项

意思是说tuyasmart_camera_android_sdk里的demo代码是有问题的吗？

**Comment by Tuya-DJ** [comment]
没有该摄像头，就代表设备还是没有配成功。

**Comment by liuxin2533** [comment]
> 没有该摄像头，就代表设备还是没有配成功。

那摄像头的提示灯表示已经正常联网，这是摄像头坏了吗？

**Comment by Tuya-DJ** [comment]
tuyasmart_camera_android_sdk里的demo代码就是tuyasmart_home_android_sdk的demo，配网模式都是一样的

**Comment by liuxin2533** [comment]
我们配网成功后无法再设备列表看到设备。麻烦能帮我们解绑下摄像头吗？ 

demo版本：release3.0.6
账号：15851423336  
配网时间：11：40分左右
APP：TuyaSmart-HomeSdkDemo

**Comment by Tuya-DJ** [comment]
设备已经移除

**Comment by Tuya-DJ** [comment]
你等会可以再配网试一下。有问题，直接说一下，我们会持续跟进的
