### ISSUE TITLE
参数问题请回复下

### ISSUE THREAD

**Issue by hyk888** [TuyaInc/tuyasmart_camera_android_sdk#12]
localKey  sdkProvider这两个参数是从哪获取的？

**Comment by hyk888** [comment]
追溯demo的代码，发现这个SDKProvide好像是p2pType

**Comment by hyk888** [comment]
追溯demo的代码，发现这个sdkProvide好像是p2pType

**Comment by Tuya-DJ** [comment]
![image](https://user-images.githubusercontent.com/46557911/65584066-e7583080-dfb2-11e9-83ec-421a77fc6328.png)

**Comment by Tuya-DJ** [comment]
![image](https://user-images.githubusercontent.com/46557911/65584193-17073880-dfb3-11e9-8e30-00febe86745b.png)

**Comment by hyk888** [comment]
deviceBean从哪可以拿到

**Comment by hyk888** [comment]
里面的代码各种封装，直接告诉我最源头的数据从哪获取吧

**Comment by Tuya-DJ** [comment]
https://tuyainc.github.io/tuyasmart_home_android_sdk_doc/zh-hans/resource/HomeManager.html

**Comment by Tuya-DJ** [comment]
建议你，先熟悉一下涂鸦homesdk的文档，再对接ipc

**Comment by hyk888** [comment]
这个我知道，我的意思是这个DeviceBean是否是设备（包括WiFi、ZigBee子设备）配网成功后返回的
DeviceBean，然后拿到localKey、sdkProvider

**Comment by Tuya-DJ** [comment]
是的
