### ISSUE TITLE
请问 onReceiveFrameYUVData 接口中YUV的具体格式

### ISSUE THREAD

**Issue by dengjinrong** [TuyaInc/tuyasmart_camera_android_sdk#15]
如题，请问接口 OnP2PCameraListener接口里面的onReceiveFrameYUVData（*）方法返回的yuv具体是什么格式 YUV420sp 还是 YUV420P还是其他。另外请教一下怎么将 Y 、U、V 转化成RGB565

**Comment by Tuya-DJ** [comment]
格式是YUV420P ，渲染请使用openGL
