### ISSUE TITLE
Timeout at queryRecordTimeSliceByDay

### ISSUE THREAD

**Issue by gatewayseguritech** [TuyaInc/tuyasmart_camera_android_sdk#18]
The consultation of videos in SD works with certain days.

We know it is a list of videos captured by motion detection. There are days that have a large number of records.

This is my code for queries

mCameraP2P.queryRecordTimeSliceByDay(yearSelected, monthSelected, daySelected, new OperationDelegateCallBack() {

            @Override

            public void onSuccess(int sessionId, int requestId, String data) {

                setListeners();

                Log.i(TAG, "Success videos by day  " + data);

            }

            @Override

            public void onFailure(int sessionId, int requestId, int errCode) {

                setListeners();

                Log.i(TAG, "Error videos by day  " + sessionId + "  " + requestId + "  " + errCode);

            }

        });

		

When working with the day 2019/12/13 the result is correct

It returns me a quantity of 37 records

Success videos by day  {"count":37,"items":[{"startTime":1576181288,"endTime":1576181340},{"startTime":1576181864,"endTime":1576181915},{"startTime":1576194978,"endTime":1576195456},{"startTime":1576196128,"endTime":1576196253},{"startTime":1576249364,"endTime":1576249479},{"startTime":1576249800,"endTime":1576249831},{"startTime":1576249864,"endTime":1576249876},{"startTime":1576250301,"endTime":1576250331},{"startTime":1576250351,"endTime":1576250365},{"startTime":1576250390,"endTime":1576250403},{"startTime":1576250419,"endTime":1576250432},{"startTime":1576250450,"endTime":1576250463},{"startTime":1576250487,"endTime":1576250501},{"startTime":1576250506,"endTime":1576250527},{"startTime":1576250818,"endTime":1576250849},{"startTime":1576251454,"endTime":1576251569},{"startTime":1576251506,"endTime":1576251520},{"startTime":1576251549,"endTime":1576251562},{"startTime":1576251580,"endTime":1576251593},{"startTime":1576251611,"endTime":1576251622},{"startTime":1576251628,"endTime":1576251650},{"startTime":1576251670,"endTime":1576251691},{"startTime":1576251719,"endTime":1576251731},{"startTime":1576251748,"endTime":1576251761},{"startTime":1576251789,"endTime":1576251799},{"startTime":1576251822,"endTime":1576251834},{"startTime":1576251860,"endTime":1576251874},{"startTime":1576251908,"endTime":1576251920},{"startTime":1576252001,"endTime":1576252022},{"startTime":1576252153,"endTime":1576252166},{"startTime":1576252182,"endTime":1576252196},{"startTime":1576252219,"endTime":1576252232},{"startTime":1576252252,"endTime":1576252264},{"startTime":1576252275,"endTime":1576252297},{"startTime":1576252310,"endTime":1576252324},{"startTime":1576252343,"endTime":1576252356},{"startTime":1576252394,"endTime":1576252408}]}

		

		

On the day 2019/12/19 the result is even faster with only 4 records

Success videos by day  {"count":4,"items":[{"startTime":1576688878,"endTime":1576688955},{"startTime":1576690052,"endTime":1576690196},{"startTime":1576774047,"endTime":1576774079},{"startTime":1576774147,"endTime":1576774162}]}

On the day 2019/12/16 an error occurs throwing the following codes

sessionId 21

requestId 113

errCode -1

Consulting directly in the SD I can verify that this day contains 100 records

Could it be due to a timeout?

I would also like to mention that Tuya's services seem intermittent, sometimes behaving very slowly regardless of the quality of the network.

**Comment by Tuya-DJ** [comment]
may be related to camera communication stability
