### ISSUE TITLE
android 监控视频流

### ISSUE THREAD

**Issue by wxiaobao** [TuyaInc/tuyasmart_camera_android_sdk#2]
public void onReceiveFrameYUVData(int sessionId, ByteBuffer y, ByteBuffer u, ByteBuffer v, int width, int height, long timestamp, Object camera)  请问一下 这个接口，那个参数是视频流，能不能给一下如何把视频流打印处理的代码？谢谢

**Comment by Tuya-DJ** [comment]
ByteBuffer y：y的数据
ByteBuffer u：u的数据
ByteBuffer v：v的数据
这三个数据给出的是画面yuv所对应的数据
