### ISSUE TITLE
参数配置

### ISSUE THREAD

**Issue by Gaiuss** [TuyaInc/tuyasmart_camera_android_sdk#20]
iNetConfigManager.setAuthorKey()
参数authorKey是什么内容？

**Comment by TuyaRockSugar** [comment]
您好，请提供下详细的接入信息，
如果是对接camera模块遇到问题，请参考：https://tuyainc.github.io/tuyasmart_camera_android_sdk_doc/zh-hans/
其他问题参考公版文档：https://tuyainc.github.io/tuyasmart_home_android_sdk_doc/zh-hans/

**Comment by Gaiuss** [comment]
请问一下这个详细的接入信息是包含什么内容？目前我们这边做的是设备配置网络的问题，应该是home app SDK。

**Comment by TuyaRockSugar** [comment]
您好，配网相关的问题可以参考文档：https://tuyainc.github.io/tuyasmart_home_android_sdk_doc/zh-hans/resource/Activator_wifi.html，也可在home SDK下提问：https://github.com/TuyaInc/tuyasmart_home_android_sdk/issues，会有专门的同事为您解决

**Comment by Gaiuss** [comment]
好的，我先参考文档试一下。
这个home SDK提问的网站，我这边打开是404

**Comment by Gaiuss** [comment]
不好意思，您发的这个文档里面，没找到相关的内容，我们这边用的是MQTT配网，当执行到这个步骤时，INetConfigManager.setAuthorKey(String authorKey);
不清除这个authorKey是个什么值，从哪里获取？

**Comment by TuyaRockSugar** [comment]
您好，配网相关的提问地址： https://github.com/TuyaInc/tuyasmart_home_android_sdk/issues

**Comment by Gaiuss** [comment]
好的，已在那边提了MQTT问题，感谢

**Comment by TuyaRockSugar** [comment]
配网问题已转交到公版SDK提问
