### ISSUE TITLE
Sound mute when controlling pt.

### ISSUE THREAD

**Issue by hoyoung222** [TuyaInc/tuyasmart_camera_android_sdk#25]
Sound mute when controlling pt.

1. watching live //  Hear sound.
2. control pt start // No sound.
3. control pt stop  // Hear sound.

Please confirm.

**Comment by TuyaRockSugar** [comment]
demo is ok？

**Comment by hoyoung222** [comment]
I'm sorry.

It seems to be a problem of the camera.
