### ISSUE TITLE
项目编译长时间卡在 Download tymodule-annotation-0.0.6.pom 

### ISSUE THREAD

**Issue by lowly360** [TuyaInc/tuyasmart_camera_android_sdk#27]
`maven {
            url 'https://maven-other.tuya.com/repository/maven-releases/'
        }`

在依赖仓库里面查看，tymodule-annotation已经去到0.0.8了，并且0.0.6的内容已经删除掉，能否优化一下这部分依赖关系

**Comment by lowly360** [comment]
![](https://s1.ax1x.com/2020/05/29/tukedf.png)

**Comment by TuyaRockSugar** [comment]
这个应该是sdk升级只升级了部分（还有部分依赖是在老的仓库下的），请按版本完整更新下
