### ISSUE TITLE
能否开放armeabi相关的so

### ISSUE THREAD

**Issue by lowly360** [TuyaInc/tuyasmart_camera_android_sdk#4]
查看aar发现，内嵌了armeabi-v7a,x86.但是因为**旧**项目的原因，项目设置的abi不得不使用armeabi.在接入摄像头的时候就找不到so了.而旧项目已经很难修改为armeabi-v7a.

请问能否考虑下在aar中把armeabi也内嵌进去？或者在github中提供armeabi的so文件（类似：[涂鸦HomeSdk](https://github.com/TuyaInc/tuyasmart_home_android_sdk/tree/master/so_libs)）

**Comment by Tuya-DJ** [comment]
我们内部评估一下，后续会通知。
