### ISSUE TITLE
类网络摄像头产品的配网问题

### ISSUE THREAD

**Issue by woodknife2019** [TuyaInc/tuyasmart_camera_android_sdk#5]
在做类似 网络摄像头产品的配网的过程中，需要中间弹出二维码进行确认绑定，在测试DEMO中没有相关接口，请问这个二维码的接口是在什么地方？

**Comment by Tuya-DJ** [comment]
https://tuyainc.github.io/tuyasmart_camera_android_sdk_doc/zh-hans/resource/wifi_config.html
