### ISSUE TITLE
摄像头怕p2pTYPE为1时，不调用onPreviewSuccess回调

### ISSUE THREAD

**Issue by huangxumin** [TuyaInc/tuyasmart_camera_android_sdk#8]
只有在P2Ptype为2时会回调这个接口，但是ios是会回调这个接口的。

**Comment by TuyaRockSugar** [comment]
是的，两套回调机制不同，目前P2Ptype ==1是不会走onPreviewSuccess回调的。

**Comment by huangxumin** [comment]
目前没有办法让p2ptype==1走这个回调吗

**Comment by TuyaRockSugar** [comment]
暂时没有这个回调；推荐使用p2ptype ==2的设备
