### ISSUE TITLE
你好，你们的android sdk提供的摄像头单例有问题

### ISSUE THREAD

**Issue by huangxumin** [TuyaInc/tuyasmart_camera_android_sdk#9]
TuyaSmartCameraFactory.generateTuyaSmartCamera(p2pType)，这个单例初始化有问题，如果初始化了p2ptype为2的摄像头，再初始化1的，就是同一个，会出现不能播放，甚至报错。需要分开1和2类型的单例初始化。

**Comment by Tuya-DJ** [comment]
如果你初始化了之后，需要调用删除的方法。然后再初始化
